### ISSUE TITLE
Joomla! 3.8.1 Checksums

### ISSUE THREAD

**Issue by titobrasolin** [Kubik-Rubik/JCS-Joomla-Checksum-Scanner#1]
Hi @Kubik-Rubik,
https://checksums.kubik-rubik.de/#overview-joomla is not updated, Joomla! 3.7.4 was released three months ago.

Do you plan to publish Joomla 3.8.1 checksums in the near future?
Thank you

**Comment by titobrasolin** [comment]
I just saw the update, thank you @Kubik-Rubik 
By the way, Joomla! 3.8.2 was released today ;-)

**Comment by Kubik-Rubik** [comment]
@titobrasolin Thank you for your comments. Just added the new version 3.8.2 to the list of supported versions (https://checksums.kubik-rubik.de/).

Cheers
